name: Continuous Deployment

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v1
    - name: Publish package to hex.pm
      uses: wesleimp/action-publish-hex@v1
      env:
        HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
